name: CI
on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json

  image_scan:
    name: Build Image and Run Docker Scout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker buildx build --load -f Dockerfile -t myapp:latest .

      # - name: Install Docker Scout
      #   run: |
      #     curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
      #     sh install-scout.sh

      # - name: Run Docker Scout
      #   run: |
      #     echo ${{secrets.REPO_TOKEN}} | docker login -u ${{secrets.REPO_USER}} --password-stdin
      #     docker scout quickview myapp:latest
      #     docker scout cves myapp:latest

      - name: Docker scout scan
        uses: docker/scout-action@v1.18.2
        with:
          # Docker Hub User
          dockerhub-user: ${{secrets.REPO_USER}}
    # Docker Hub PAT
          dockerhub-password: ${{secrets.REPO_TOKEN}}
          command: quickview, cves
          only-severities: critical, high
          sarif-file: scout_report.sarif
          
      - name: Upload scout Report
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: scout findings
          path: scout_report.sarif
